USE Basketball;
GO

INSERT INTO Team (Id, Name, State, City, Stadium, Conference) VALUES
('ATL', 'Hawks', 'Georgia', 'Atlanta', 'State Farm Arena', 'E'),
('BOS', 'Celtics', 'Massachusetts', 'Boston', 'TD Garden', 'E'),
('BKN', 'Nets', 'New York', 'Brooklyn', 'Barclays Center', 'E'),
('CHA', 'Hornets', 'North Carolina', 'Charlotte', 'Spectrum Center', 'E'),
('CHI', 'Bulls', 'Illinois', 'Chicago', 'United Center', 'E'),
('CLE', 'Cavaliers', 'Ohio', 'Cleveland', 'Rocket Mortgage FieldHouse', 'E'),
('DAL', 'Mavericks', 'Texas', 'Dallas', 'American Airlines Center', 'W'),
('DEN', 'Nuggets', 'Colorado', 'Denver', 'Ball Arena', 'W'),
('DET', 'Pistons', 'Michigan', 'Detroit', 'Little Caesars Arena', 'E'),
('GSW', 'Warriors', 'California', 'San Francisco', 'Chase Center', 'W'),
('HOU', 'Rockets', 'Texas', 'Houston', 'Toyota Center', 'W'),
('IND', 'Pacers', 'Indiana', 'Indianapolis', 'Gainbridge Fieldhouse', 'E'),
('LAC', 'Clippers', 'California', 'Los Angeles', 'Crypto.com Arena', 'W'),
('LAL', 'Lakers', 'California', 'Los Angeles', 'Crypto.com Arena', 'W'),
('MEM', 'Grizzlies', 'Tennessee', 'Memphis', 'FedExForum', 'W'),
('MIA', 'Heat', 'Florida', 'Miami', 'Kaseya Center', 'E'),
('MIL', 'Bucks', 'Wisconsin', 'Milwaukee', 'Fiserv Forum', 'E'),
('MIN', 'Timberwolves', 'Minnesota', 'Minneapolis', 'Target Center', 'W'),
('NOP', 'Pelicans', 'Louisiana', 'New Orleans', 'Smoothie King Center', 'W'),
('NYK', 'Knicks', 'New York', 'New York', 'Madison Square Garden', 'E'),
('OKC', 'Thunder', 'Oklahoma', 'Oklahoma City', 'Paycom Center', 'W'),
('ORL', 'Magic', 'Florida', 'Orlando', 'Amway Center', 'E'),
('PHI', '76ers', 'Pennsylvania', 'Philadelphia', 'Wells Fargo Center', 'E'),
('PHX', 'Suns', 'Arizona', 'Phoenix', 'Footprint Center', 'W'),
('POR', 'Trail Blazers', 'Oregon', 'Portland', 'Moda Center', 'W'),
('SAC', 'Kings', 'California', 'Sacramento', 'Golden 1 Center', 'W'),
('SAS', 'Spurs', 'Texas', 'San Antonio', 'AT&T Center', 'W'),
('TOR', 'Raptors', 'Ontario', 'Toronto', 'Scotiabank Arena', 'E'),
('UTA', 'Jazz', 'Utah', 'Salt Lake City', 'Delta Center', 'W'),
('WAS', 'Wizards', 'District of Columbia', 'Washington', 'Capital One Arena', 'E');
