USE Basketball;
GO

INSERT INTO Team (Id, TeamName, TeamState) VALUES
('ATL', 'Hawks', 'Georgia'),
('BOS', 'Celtics', 'Massachusetts'),
('BKN', 'Nets', 'New York'),
('CHA', 'Hornets', 'North Carolina'),
('CHI', 'Bulls', 'Illinois'),
('CLE', 'Cavaliers', 'Ohio'),
('DAL', 'Mavericks', 'Texas'),
('DEN', 'Nuggets', 'Colorado'),
('DET', 'Pistons', 'Michigan'),
('GSW', 'Warriors', 'California'),
('HOU', 'Rockets', 'Texas'),
('IND', 'Pacers', 'Indiana'),
('LAC', 'Clippers', 'California'),
('LAL', 'Lakers', 'California'),
('MEM', 'Grizzlies', 'Tennessee'),
('MIA', 'Heat', 'Florida'),
('MIL', 'Bucks', 'Wisconsin'),
('MIN', 'Timberwolves', 'Minnesota'),
('NOP', 'Pelicans', 'Louisiana'),
('NYK', 'Knicks', 'New York'),
('OKC', 'Thunder', 'Oklahoma'),
('ORL', 'Magic', 'Florida'),
('PHI', '76ers', 'Pennsylvania'),
('PHX', 'Suns', 'Arizona'),
('POR', 'Trail Blazers', 'Oregon'),
('SAC', 'Kings', 'California'),
('SAS', 'Spurs', 'Texas'),
('TOR', 'Raptors', 'Ontario'),
('UTA', 'Jazz', 'Utah'),
('WAS', 'Wizards', 'District of Columbia');
