// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Game {
  Id integer [primary key]
  VisitorsTeamId varchar
  HomeTeamId varchar
  MatchDate date
}

Table Team {
  Id varchar [primary key]
  TeamName varchar
  TeamState varchar
}

Table Scalation {
   SeasonId char [primary key]
   TeamId varchar [primary key]
   Ranking integer
}

Table Season {
  Id char [primary key]
}

Table Player {
  Id integer [primary key]
  PlayerName varchar
  DateOfBirth date
  Position varchar
}

Table Selection {
  Id integer [primary key]
  PlayerId integer [unique]
  SeasonId char [unique]
  TeamId varchar [unique]
  Jersey integer
}

Table Participation {
  Id integer [primary key]
  GameId integer 
  SelectionId integer
  Quarter integer
}

Table Play {
  Id integer [primary key]
  ParticipationId integer
  PlayType integer
  Amount integer
}

Ref: Game.Id > Participation.GameId
Ref: Game.HomeTeamId > Scalation.TeamId
Ref: Game.VisitorsTeamId > Scalation.TeamId
Ref: Participation.Id > Play.ParticipationId
Ref: Scalation.SeasonId > Season.Id
Ref: Scalation.TeamId > Team.Id
Ref: Scalation.SeasonId > Selection.SeasonId
Ref: Scalation.TeamId > Selection.TeamId
Ref: Selection.Id > Participation.SelectionId
Ref: Player.Id > Selection.PlayerId